# Generated by Django 5.0.2 on 2024-02-27 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('restroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restroom.restroom')),
            ],
        ),
    ]
