# Generated by Django 5.0.2 on 2024-02-27 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
        ('restroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='restroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='restroom.restroom'),
        ),
    ]
