# Generated by Django 5.0.2 on 2024-02-27 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restroom', '0002_alter_restroom_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('restroom', models.ManyToManyField(related_name='tags', to='restroom.restroom')),
            ],
        ),
    ]
