# Generated by Django 5.0.2 on 2024-03-09 09:00

import core.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, upload_to=core.utils.functions.get_image_upload_path),
        ),
    ]
